name: Windows Build

on:
  push:
    branches: [ "gha-testing" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install 7zip
        uses: milliewalky/setup-7-zip@v2

      - name: Verify 7zip install
        run: 7z --help
        shell: powershell
        

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build c++23 std library module
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl /std:c++latest /EHsc /nologo /W4 /c "%VCToolsInstallDir%\modules\std.ixx"

      - name: Build Solution (Release x64, C++23)
        shell: cmd
        run: |
          msbuild nemulator.sln /t:Build /p:Configuration=Release /p:Platform=x64 /p:LangVersion=stdcpplatest /p:BuildStlModules=true

      - name: Package Build Artifacts
        shell: powershell
        run: |
          $sha = "${{ github.sha }}".Substring(0,7)
          mkdir artifacts
          # Adjust paths to where your binaries are output
          Copy-Item "Release\nemulator.exe" "artifacts\nemulator-$sha.exe"

      - name: Create or Update Preview Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Preview Build"
          prerelease: true
          draft: true
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}