name: Windows Build

on:
  push:
    branches: [ "gha-testing" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install 7zip
        uses: milliewalky/setup-7-zip@v2

      - name: Verify 7zip install
        run: 7z --help
        shell: powershell
        

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution (Release x64, C++23)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
          CL.exe /c /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\shared" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\winrt" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\cppwinrt" /I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8.1\Include\um" /Zi /nologo /W4 /WX- /diagnostics:column /MP /FS /O2 /Oi /GL /D WIN64 /D NDEBUG /D _WINDOWS /D _CRT_SECURE_NO_WARNINGS /Gm- /EHsc /MT /GS /Gy /arch:AVX /fp:fast /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /FAs /Fa"Release\\" /scanDependencies "Release\\" /external:W4 /Gd /interface /wd4334 /FC /errorReport:queue  /TP "%VCToolsInstallDir%\modules\std.ixx"
          msbuild nemulator.sln /t:Build /p:Configuration=Release /p:Platform=x64 /p:LanguageStandard=stdcpplatest /p:EnableModules=true

      - name: Package Build Artifacts
        shell: powershell
        run: |
          $sha = "${{ github.sha }}".Substring(0,7)
          mkdir artifacts
          # Adjust paths to where your binaries are output
          Copy-Item "Release\nemulator.exe" "artifacts\nemulator-$sha.exe"

      - name: Create or Update Preview Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Preview Build"
          prerelease: true
          draft: true
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}